[book]
authors = ["CeresDB Authors"]
language = "en"
multilingual = true
src = "src/en"
title = "CeresDB Documentation"

[build]
use-default-preprocessors = false

[preprocessor.links]

[[output.i18n.translations]]
src = "src/cn"
language = "cn"
translators = ["CeresDB Authors"]
title = "CeresDB 文档"

[output.random]
command = "/bin/bash ../../move.sh"

[output.html]
cname = "docs.ceresdb.io"
git-repository-url = "https://github.com/CeresDB/ceresdb"
edit-url-template = "https://github.com/CeresDB/docs/edit/main/docs/{path}"

[output.html.fold]
enable = true

