[book]
authors = ["CeresDB Authors"]
language = "en"
multilingual = true
src = "src/en"
title = "CeresDB Documentation"

[[output.i18n.translations]]
src = "src/cn"
language = "cn"
translators = ["CeresDB Authors"]
title = "CeresDB 文档"

[output.random]
command = "/bin/bash ../../move.sh"

[output.html]
cname = "docs.ceresdb.io"

[output.html.fold]
enable = true
